### ISSUE TITLE
Boost version compatibility issue 

### ISSUE THREAD

**Issue by DanSava** [equinor/Carolina#17]
Carolina installation fails on Ubuntu if using the latest version of libboost-all-dev  and libboost-dev currently at 1.65_1 
using liboost-all-dev 1.62 Carolina installs successfuly.

**Comment by andreabrambilla** [comment]
Yes, this is a kind of known issue, it is due to some changes in the API in version 1.65 (if I remember correctly). 
All the systems we currently use Carolina on have older versions of boost (Travis builds with version 1.54) so we never bothered updating it.

But good that you bring this up, we can have this issue as a reminder that we need to update it sooner or later

**Comment by agchitu** [comment]
Hi guys,
The limitation comes from dakota and it shows in carolina as well.
 
The recommended boost version on Dakota website is still 1.53: https://dakota.sandia.gov/content/boost
However, I have tried with 1.54 (as in Travis) and just today with 1.58 and it works fine.
In order to build on a specific boost version I would recommend to build boost manually and not through apt-get  or yum, etc and then properly set the boost_root and co. Make sure that you also build the boost_python library (add --with-python=path/to/python) when configuring boost.

**Comment by agchitu** [comment]
The issue with Boost comes from the fact that version 1.65 of Boost removes the numeric namespace and replace it with numpy. I have created a PR that tries to solve this issue because, I needed a newer Boost that builds with Python3
